# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mcpx < Formula
  desc "MCP servers as CLI tools — built for AI agents"
  homepage "https://github.com/codestz/mcpx"
  version "1.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/codestz/mcpx/releases/download/v1.4.0/mcpx_1.4.0_darwin_amd64.tar.gz"
      sha256 "d68582c673ab1c2af5d5aac62381fa94a61552ea857b88da5b8e60e23935b583"

      define_method(:install) do
        bin.install "mcpx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/codestz/mcpx/releases/download/v1.4.0/mcpx_1.4.0_darwin_arm64.tar.gz"
      sha256 "d5100730a33c0d5152ace0454975eb9aac7be4d4cf138c2a48eb67d084a20546"

      define_method(:install) do
        bin.install "mcpx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/codestz/mcpx/releases/download/v1.4.0/mcpx_1.4.0_linux_amd64.tar.gz"
      sha256 "170fe6a65e6c02b2e3a16c3a0c28733740f317fd0d0d998ce543a601a9f93141"
      define_method(:install) do
        bin.install "mcpx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/codestz/mcpx/releases/download/v1.4.0/mcpx_1.4.0_linux_arm64.tar.gz"
      sha256 "d2ca33ddf602b446732b946958d8cff0ee2d6ebc5a04ba66b4e8a7299ea7ddee"
      define_method(:install) do
        bin.install "mcpx"
      end
    end
  end

  test do
    system "#{bin}/mcpx", "version"
  end
end
