# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mcpx < Formula
  desc "MCP servers as CLI tools — built for AI agents"
  homepage "https://github.com/codestz/mcpx"
  version "2.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/codestz/mcpx/releases/download/v2.0.0/mcpx_2.0.0_darwin_amd64.tar.gz"
      sha256 "1c30950e8d370cc8712ebae6764db0fce3e923d27faba48cd07b5f26e04c6d65"

      define_method(:install) do
        bin.install "mcpx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/codestz/mcpx/releases/download/v2.0.0/mcpx_2.0.0_darwin_arm64.tar.gz"
      sha256 "a191b9f68b521fd9462583a426b70684462c94f87ecbbfc61ae6b195bd6f0a99"

      define_method(:install) do
        bin.install "mcpx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/codestz/mcpx/releases/download/v2.0.0/mcpx_2.0.0_linux_amd64.tar.gz"
      sha256 "8b19897037f6a5a78e03ad93820a2c4ceeddfe17d9faceeace5adaddf1a7c8cd"
      define_method(:install) do
        bin.install "mcpx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/codestz/mcpx/releases/download/v2.0.0/mcpx_2.0.0_linux_arm64.tar.gz"
      sha256 "55cf739b83b707965d5dbea2fb0fb01b0449b5556d2f2d19e410e36cad41977a"
      define_method(:install) do
        bin.install "mcpx"
      end
    end
  end

  test do
    system "#{bin}/mcpx", "version"
  end
end
